import pandas as pd
ak=pd.read_excel(r"C:\Users\UAKHPAL\OneDrive - BUNGE\Desktop\DBMS mapping darta\Daily Rollout Working files\Total_Rollout_Status.xlsx",sheet_name='Rollout data')
import pyautogui
import datetime
from datetime import timedelta 
x=datetime.datetime.now()-timedelta(days=1)
pyautogui.leftClick(x=71,y=751)
pyautogui.write("SAP")
pyautogui.hotkey('enter')
pyautogui.sleep(8)
pyautogui.getWindowsWithTitle('SAP Logon Pad 760')[0].maximize()
pyautogui.leftClick(x=1269,y=418)
pyautogui.scroll(50000)
pyautogui.scroll(-50000)
pyautogui.scroll(50000)
pyautogui.sleep(3)
pyautogui.doubleClick(x=882,y=121)
pyautogui.sleep(7)
pyautogui.leftClick(x=167,y=208)
pyautogui.sleep(3)
pyautogui.write("UAKHPAL")
pyautogui.sleep(2)
pyautogui.leftClick(x=159,y=226)
pyautogui.write("Valeni@1435")
pyautogui.sleep(2)
pyautogui.hotkey('enter')
pyautogui.sleep(5)
pyautogui.leftClick(x=84,y=57)
pyautogui.write("yind_inv_detail_rep")
pyautogui.hotkey('enter')
pyautogui.sleep(3)
pyautogui.hotkey('Shift','f5')
pyautogui.sleep(2)
pyautogui.hotkey('f8')
y1=x.day
y1=str(y1)
y2=x.month
y2=str(y2)
y3=x.year
y3=str(y3)
y=y1+"."+y2+"."+y3
pyautogui.sleep(3)
pyautogui.leftClick(x=269,y=250)
pyautogui.write(y)
pyautogui.sleep(3)
pyautogui.leftClick(x=451,y=252)
pyautogui.write(y)
pyautogui.leftClick(x=572,y=315)
pyautogui.sleep(2)
ak1=ak.iloc[0:,1]
ak1.to_clipboard(index=False,header=False)
pyautogui.leftClick(x=657,y=517)
pyautogui.sleep(5)
pyautogui.hotkey('f8')
pyautogui.sleep(2)
pyautogui.hotkey('f8')
